- name: install epel-release
  action: "{{ ansible_pkg_mgr }} name=epel-release state=latest"

- name: nginx installation
  action: "{{ ansible_pkg_mgr }} name=nginx state=present"

- name: curl nginx.com
  template:
    src: index.j2
    dest: /usr/share/nginx/html/index.html
    mode: 0644
    backup: yes
  notify:
    - WebSV_Restart       # curl 로 끌어온 내용에 변경이 있다면 'restart web' 실행해라!

- name: disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
